import { useState } from 'react'
import type { TeammateInput, ProjectInput, Project, ProvisionResult } from '../types'

interface ProjectFormProps {
  onSuccess: (project: Project, provisionResult?: ProvisionResult) => void
}

interface MemberState {
  name: string
  github_username: string
}

const DEFAULT_MEMBERS: MemberState[] = [
  { name: 'Alice', github_username: 'alice' },
  { name: 'Bob', github_username: 'bob' },
  { name: 'Charlie', github_username: 'charlie' },
  { name: 'Dana', github_username: 'dana' },
  { name: 'Evan', github_username: 'evan' },
  { name: 'Fiona', github_username: 'fiona' },
]

const INSPIRATION_PRESETS = [
  {
    title: '🎨 Real-Time Whiteboard',
    prompt: 'A real-time collaborative whiteboard app with live cursor tracking, voice channels, and interactive canvas drawing for hackathon teams.',
  },
  {
    title: '🤖 DevOps Incident AI',
    prompt: 'An AI-powered DevOps agent that monitors cloud alerts, inspects container logs, diagnoses root causes, and suggests incident remediation scripts.',
  },
  {
    title: '🏃 Health & Habit Tracker',
    prompt: 'A wellness and habit tracker that logs daily routines, provides AI coaching insights, and gamifies team fitness challenges.',
  },
  {
    title: '🛡️ Web3 Smart Contract Auditor',
    prompt: 'A static analysis security tool that scans Solidity smart contracts for reentrancy and access-control vulnerabilities with interactive remediation diffs.',
  },
]

export default function ProjectForm({ onSuccess }: ProjectFormProps) {
  // Wizard step: 1 = Team Setup, 2 = Problem Statement, 3 = Divided Work & Launch
  const [step, setStep] = useState(1)

  // Step 1: Team Setup
  const [teamName, setTeamName] = useState('HackSquad')
  const [teamSize, setTeamSize] = useState<number>(3)
  const [members, setMembers] = useState<MemberState[]>(DEFAULT_MEMBERS.slice(0, 3))

  // Step 2: Problem Statement
  const [ideaPrompt, setIdeaPrompt] = useState('')
  const [decomposing, setDecomposing] = useState(false)
  const [decomposeError, setDecomposeError] = useState<string | null>(null)

  // Step 3: Divided Work (Generated by AI)
  const [divided, setDivided] = useState(false)
  const [projectName, setProjectName] = useState('')
  const [techStack, setTechStack] = useState('')
  const [conventions, setConventions] = useState('')
  const [summary, setSummary] = useState('')
  const [allocatedTeammates, setAllocatedTeammates] = useState<TeammateInput[]>([])

  // Validation
  const [membersTouched, setMembersTouched] = useState(false)
  const hasEmptyMembers = members.slice(0, teamSize).some((m) => !m.name.trim())

  // GitHub Launch Options
  const [existingRepoUrl, setExistingRepoUrl] = useState('')
  const [newRepoName, setNewRepoName] = useState('')
  const [githubPat, setGithubPat] = useState('')
  const [demoMode, setDemoMode] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [submitProgress, setSubmitProgress] = useState<string | null>(null)
  const [submitError, setSubmitError] = useState<string | null>(null)

  const handleRepoUrlChange = (url: string) => {
    setExistingRepoUrl(url)
    const clean = url.trim().replace(/\.git$/, '').replace(/\/+$/, '')
    const parts = clean.split('/')
    if (parts.length >= 2) {
      const extractedName = parts[parts.length - 1]
      if (extractedName && (!teamName || teamName === 'HackSquad' || teamName === 'my-project')) {
        setTeamName(extractedName)
      }
    }
  }

  // Adjust member list when teamSize changes
  const handleTeamSizeChange = (newSize: number) => {
    setTeamSize(newSize)
    setMembers((prev) => {
      const next = [...prev]
      while (next.length < newSize) {
        const fallback = DEFAULT_MEMBERS[next.length] || {
          name: `Teammate ${next.length + 1}`,
          github_username: `member-${next.length + 1}`,
        }
        next.push(fallback)
      }
      return next.slice(0, newSize)
    })
  }

  // Update a single member's name
  const handleMemberNameChange = (index: number, name: string) => {
    setMembers((prev) =>
      prev.map((m, idx) =>
        idx === index
          ? {
              name,
              github_username: name.toLowerCase().replace(/[^a-z0-9_-]/g, '') || `member-${idx + 1}`,
            }
          : m
      )
    )
  }

  // Validate step 1 and move to step 2
  const handleNextToStep2 = () => {
    setMembersTouched(true)
    if (hasEmptyMembers) return
    if (!teamName.trim()) return
    setStep(2)
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  // Divide the work via AI (Grok / Groq / Fallback)
  const handleDivideWork = async (promptOverride?: string) => {
    setMembersTouched(true)
    if (hasEmptyMembers) {
      setDecomposeError('All team member names are required before dividing work.')
      return
    }
    const promptToUse = promptOverride || ideaPrompt
    if (!promptToUse.trim()) {
      setDecomposeError('Please describe what your team is building (or select an idea preset).')
      return
    }

    setDecomposing(true)
    setDecomposeError(null)

    try {
      const payload = {
        teamName: teamName.trim() || 'my-project',
        teamSize,
        teammateRoles: members.slice(0, teamSize).map((m) => ({
          name: m.name.trim() || 'Teammate',
          githubUsername: m.github_username.trim().replace(/^@/, '') || 'member',
        })),
        ideaPrompt: promptToUse.trim(),
      }

      const res = await fetch('/api/ai/decompose', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      })

      const data = await res.json()
      if (!res.ok || !data.success) {
        throw new Error(data.error || 'Failed to divide work')
      }

      const result = data.data
      setProjectName(result.projectName)
      setNewRepoName(result.projectName)
      setSummary(result.description)
      setTechStack(result.techStack)
      setConventions(result.sharedConventions)
      setAllocatedTeammates(
        result.teammates.map((tm: any) => ({
          name: tm.name,
          github_username: tm.githubUsername,
          task_description: tm.taskDescription,
          owned_paths: tm.ownedPaths,
        }))
      )
      setDivided(true)

      // Auto-advance to step 3 after successful decomposition
      setStep(3)
      window.scrollTo({ top: 0, behavior: 'smooth' })
    } catch (err: any) {
      setDecomposeError(err.message || 'An error occurred while dividing the work.')
    } finally {
      setDecomposing(false)
    }
  }

  // Final Launch & Provision
  const handleLaunch = async (e: React.FormEvent) => {
    e.preventDefault()
    setSubmitError(null)
    setSubmitting(true)
    setSubmitProgress('Saving project brief...')

    try {
      const projectPayload: ProjectInput = {
        name: projectName || teamName.toLowerCase().replace(/[^a-z0-9-_]/g, '-'),
        description: summary.trim(),
        tech_stack: techStack.trim(),
        shared_conventions: conventions.trim(),
        github_repo_url: existingRepoUrl.trim() || undefined,
        teammates: allocatedTeammates,
      }

      // 1. Create project in backend
      const res = await fetch('/api/projects', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(projectPayload),
      })

      if (!res.ok) {
        const errData = await res.json()
        throw new Error(errData.error || 'Failed to create project')
      }

      const project: Project = await res.json()

      // 2. Provision repo & cut branches
      setSubmitProgress(
        existingRepoUrl.trim()
          ? 'Connecting to repository, setting up conventions & branches...'
          : 'Setting up conventions & cutting teammate branches...'
      )
      const provisionRes = await fetch(`/api/projects/${project.id}/provision`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          repoName: !existingRepoUrl.trim() ? (newRepoName.trim() || projectName) : undefined,
          existingRepoUrl: existingRepoUrl.trim() || undefined,
          pat: githubPat.trim() || undefined,
          isDemo: demoMode,
        }),
      })

      if (provisionRes.ok) {
        const provData: ProvisionResult = await provisionRes.json()
        project.github_repo_url = provData.repoUrl
        onSuccess(project, provData)
      } else {
        onSuccess(project)
      }
    } catch (err: any) {
      setSubmitError(err.message || 'Failed to launch project')
    } finally {
      setSubmitting(false)
      setSubmitProgress(null)
    }
  }

  const STEP_LABELS = ['Team Setup', 'Problem Statement', 'Launch']

  return (
    <div className="project-form" id="simple-project-form">
      {/* ---- Step Progress Indicator ---- */}
      <div className="wizard-progress" id="wizard-progress">
        {STEP_LABELS.map((label, idx) => {
          const stepNum = idx + 1
          const isActive = step === stepNum
          const isCompleted = step > stepNum
          return (
            <div
              key={stepNum}
              className={`wizard-step ${isActive ? 'wizard-step--active' : ''} ${isCompleted ? 'wizard-step--done' : ''}`}
              onClick={() => {
                // Allow clicking back to completed steps
                if (isCompleted) {
                  setStep(stepNum)
                  window.scrollTo({ top: 0, behavior: 'smooth' })
                }
              }}
              role={isCompleted ? 'button' : undefined}
              tabIndex={isCompleted ? 0 : undefined}
              style={{ cursor: isCompleted ? 'pointer' : 'default' }}
            >
              <span className="wizard-step__number mono">
                {isCompleted ? '✓' : `0${stepNum}`}
              </span>
              <span className="wizard-step__label">{label}</span>
            </div>
          )
        })}
        <div className="wizard-progress__track">
          <div
            className="wizard-progress__fill"
            style={{ width: `${((step - 1) / (STEP_LABELS.length - 1)) * 100}%` }}
          />
        </div>
      </div>

      {/* ============================================================ */}
      {/* STEP 1: GITHUB REPOSITORY & TEAM SETUP                       */}
      {/* ============================================================ */}
      {step === 1 && (
        <section className="form-section wizard-page" id="step-team-setup">
          <h2 className="section-title">
            <span className="section-icon mono">01</span>
            GitHub Repo & Team Setup
          </h2>

          {/* GitHub Repository Link */}
          <div className="field" style={{ marginBottom: 'var(--space-md)' }}>
            <label htmlFor="input-repo-link" className="field-label" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <span>🔗 GitHub Repository URL</span>
              <span className="mono muted" style={{ fontSize: '0.75rem' }}>Paste your newly created repo link</span>
            </label>
            <input
              id="input-repo-link"
              type="url"
              className="input mono"
              placeholder="e.g. https://github.com/your-username/your-hackathon-repo"
              value={existingRepoUrl}
              onChange={(e) => handleRepoUrlChange(e.target.value)}
            />
            <span className="muted" style={{ fontSize: '0.75rem', marginTop: '4px', display: 'block' }}>
              Each teammate works on their assigned branch and then pushes / merges back into <code>main</code>.
            </span>
          </div>

          {/* Team Name & Size Row */}
          <div className="field-row two-col">
            <div className="field">
              <label htmlFor="input-team-name" className="field-label">
                Team / Project Name
              </label>
              <input
                id="input-team-name"
                type="text"
                className="input mono"
                placeholder="e.g. CloudNavigators"
                value={teamName}
                onChange={(e) => setTeamName(e.target.value)}
                required
              />
            </div>

            <div className="field">
              <label htmlFor="select-team-size" className="field-label">
                Team Size
              </label>
              <select
                id="select-team-size"
                className="input select-input mono"
                value={teamSize}
                onChange={(e) => handleTeamSizeChange(parseInt(e.target.value, 10))}
              >
                <option value={2}>2 Teammates</option>
                <option value={3}>3 Teammates</option>
                <option value={4}>4 Teammates</option>
                <option value={5}>5 Teammates</option>
                <option value={6}>6 Teammates</option>
              </select>
            </div>
          </div>

          {/* Member Names */}
          <div style={{ marginTop: 'var(--space-sm)' }}>
            <span className="field-label mono">TEAM MEMBERS:</span>
            <div className="members-grid">
              {members.slice(0, teamSize).map((member, idx) => (
                <div key={idx} className="member-card-setup">
                  <div className="member-card-header">
                    <span className="member-number-badge">MEMBER {idx + 1}</span>
                  </div>

                  <div className="field">
                    <input
                      type="text"
                      className={`input mono ${membersTouched && !member.name.trim() ? 'input-invalid' : ''}`}
                      style={{ fontSize: '0.875rem', padding: '8px 12px' }}
                      placeholder={`Name (e.g. Alice)`}
                      value={member.name}
                      onChange={(e) => handleMemberNameChange(idx, e.target.value)}
                      onBlur={() => setMembersTouched(true)}
                      required
                    />
                    {membersTouched && !member.name.trim() && (
                      <span className="validation-error">⚠ Name is required</span>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Next Button */}
          <div className="wizard-nav">
            <div />
            <button
              type="button"
              className="btn btn-primary"
              onClick={handleNextToStep2}
              disabled={hasEmptyMembers || !teamName.trim()}
              id="btn-next-step2"
            >
              Next → Problem Statement
            </button>
          </div>
        </section>
      )}

      {/* ============================================================ */}
      {/* STEP 2: PROBLEM STATEMENT & DIVIDE WORK                      */}
      {/* ============================================================ */}
      {step === 2 && (
        <section className="form-section wizard-page" id="step-problem-statement">
          <h2 className="section-title">
            <span className="section-icon mono">02</span>
            Problem Statement
          </h2>

          <p className="section-description">
            Describe what you want to build. You can also pick a preset idea below to start instantly.
          </p>

          {/* Quick Inspiration Presets */}
          <div className="ai-preset-chips">
            {INSPIRATION_PRESETS.map((preset, idx) => (
              <button
                key={idx}
                type="button"
                className="ai-preset-chip"
                onClick={() => {
                  setIdeaPrompt(preset.prompt)
                  setDecomposeError(null)
                  handleDivideWork(preset.prompt)
                }}
              >
                {preset.title}
              </button>
            ))}
          </div>

          {/* Textarea */}
          <div className="field" style={{ marginTop: 'var(--space-sm)' }}>
            <textarea
              id="idea-prompt-input"
              className="input textarea mono"
              rows={3}
              placeholder="e.g. An automated drone delivery platform that schedules flights and runs collision avoidance..."
              value={ideaPrompt}
              onChange={(e) => setIdeaPrompt(e.target.value)}
            />
          </div>

          {decomposeError && (
            <div className="error-banner" style={{ marginTop: 'var(--space-xs)' }}>
              {decomposeError}
            </div>
          )}

          {/* Navigation: Back & Divide */}
          <div className="wizard-nav">
            <button
              type="button"
              className="btn btn-secondary"
              onClick={() => {
                setStep(1)
                window.scrollTo({ top: 0, behavior: 'smooth' })
              }}
              id="btn-back-step1"
            >
              ← Back
            </button>
            <button
              type="button"
              className="btn btn-primary"
              style={{ fontSize: '0.9375rem', padding: '10px 20px' }}
              onClick={() => handleDivideWork()}
              disabled={decomposing || !ideaPrompt.trim() || hasEmptyMembers}
              id="btn-divide-work"
            >
              {decomposing ? (
                <>
                  <span className="spinner" style={{ width: 14, height: 14, marginRight: '8px' }} />
                  <span>Dividing Work & Allocating Paths...</span>
                </>
              ) : divided ? (
                '🔄 Re-Divide Work'
              ) : (
                '✨ Divide & Allocate Work'
              )}
            </button>
          </div>
        </section>
      )}

      {/* ============================================================ */}
      {/* STEP 3: DIVIDED WORK & LAUNCH                                */}
      {/* ============================================================ */}
      {step === 3 && divided && (
        <form onSubmit={handleLaunch} id="step-divided-work" className="wizard-page">
          <section className="form-section">
            <div className="section-title-row">
              <h2 className="section-title">
                <span className="section-icon mono">03</span>
                Divided Work Plan
              </h2>
              <span className="security-tag mono" style={{ color: 'var(--accent)' }}>
                ✓ Zero Merge Conflicts Guaranteed
              </span>
            </div>

            {/* Architecture Overview Pill */}
            <div className="clean-callout">
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span className="mono" style={{ color: 'var(--accent)', fontWeight: 600, fontSize: '0.875rem' }}>
                  📦 {projectName}
                </span>
                <span className="mono muted" style={{ fontSize: '0.75rem' }}>
                  {techStack}
                </span>
              </div>
              <p style={{ fontSize: '0.8125rem', color: 'var(--text-secondary)', margin: 0 }}>
                {summary}
              </p>
            </div>

            {/* Clean Teammate Allocation Cards */}
            <div className="divided-work-list">
              {allocatedTeammates.map((mate, i) => (
                <div key={i} className="divided-card">
                  <div className="divided-card-head">
                    <span className="divided-name">{mate.name}</span>
                    <span className="mono muted" style={{ fontSize: '0.75rem' }}>
                      ↳ Branch: <code>{`${mate.task_description.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 18)}-${mate.github_username}`}</code>
                    </span>
                  </div>

                  <div className="divided-task-text">
                    <strong>Assigned:</strong> {mate.task_description}
                  </div>

                  <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <span className="field-label mono" style={{ fontSize: '0.6875rem' }}>Isolated Paths:</span>
                    <div className="ai-tm-paths mono">
                      {mate.owned_paths.map((p, idx) => (
                        <span key={idx} className="path-tag">
                          {p}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {/* Launch / GitHub Cloud Provisioning */}
            <div style={{ marginTop: 'var(--space-md)', paddingTop: 'var(--space-md)', borderTop: '1px solid var(--border-subtle)' }}>
              <div className="clean-callout" style={{ marginBottom: 'var(--space-md)' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '8px' }}>
                  <div>
                    <span className="mono" style={{ color: 'var(--accent)', fontWeight: 600, fontSize: '0.875rem' }}>
                      🔗 Target Repository: {existingRepoUrl ? existingRepoUrl : 'Simulated GitHub Workspace'}
                    </span>
                    <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', margin: '4px 0 0 0' }}>
                      <strong>Lifecycle:</strong> Each teammate creates &amp; works on their dedicated branch, then opens a PR to merge into <code>main</code>.
                    </p>
                  </div>
                  <span className="security-tag mono">
                    Target Branch: main
                  </span>
                </div>
              </div>

              {/* If repo wasn't entered in Step 1, allow entering it here */}
              {!existingRepoUrl && (
                <div className="field" style={{ marginBottom: 'var(--space-sm)' }}>
                  <label htmlFor="existing-repo-url" className="field-label">
                    GitHub Repository URL
                  </label>
                  <input
                    id="existing-repo-url"
                    type="text"
                    className="input mono"
                    placeholder="https://github.com/your-username/your-hackathon-repo"
                    value={existingRepoUrl}
                    onChange={(e) => setExistingRepoUrl(e.target.value)}
                  />
                </div>
              )}
              <div className="field" style={{ marginBottom: 'var(--space-sm)' }}>
                <label htmlFor="github-pat" className="field-label">GitHub fine-grained token (optional)</label>
                <input
                  id="github-pat"
                  type="password"
                  autoComplete="off"
                  className="input mono"
                  placeholder="Required to create branches in a real repository"
                  value={githubPat}
                  onChange={(e) => setGithubPat(e.target.value)}
                />
                <span className="muted" style={{ fontSize: '0.75rem', marginTop: '4px', display: 'block' }}>
                  Used only for this request and never saved. Leave blank to use demo mode.
                </span>
              </div>
              <label className="field-label" style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
                <input type="checkbox" checked={demoMode} onChange={(e) => setDemoMode(e.target.checked)} />
                Force demo mode (no repository changes)
              </label>
            </div>

            {submitError && (
              <div className="error-banner" style={{ marginTop: 'var(--space-sm)' }}>
                {submitError}
              </div>
            )}

            {submitProgress && (
              <div className="progress-banner" style={{ marginTop: 'var(--space-sm)' }}>
                <span className="spinner" />
                <span>{submitProgress}</span>
              </div>
            )}

            {/* Navigation: Back & Launch */}
            <div className="wizard-nav" style={{ marginTop: 'var(--space-md)' }}>
              <button
                type="button"
                className="btn btn-secondary"
                onClick={() => {
                  setStep(2)
                  window.scrollTo({ top: 0, behavior: 'smooth' })
                }}
                id="btn-back-step2"
              >
                ← Back
              </button>
              <button
                type="submit"
                className="btn btn-primary"
                style={{ fontSize: '1rem', padding: '12px 24px' }}
                disabled={submitting}
                id="submit-btn"
              >
                {submitting ? 'Launching Team...' : '🚀 Launch Team & Cut Branches'}
              </button>
            </div>
          </section>
        </form>
      )}
    </div>
  )
}
