import { useState } from 'react'
import type { TeammateInput, ProjectInput, Project, ProvisionResult } from '../types'

interface ProjectFormProps {
  onSuccess: (project: Project, provisionResult?: ProvisionResult) => void
}

interface MemberState {
  name: string
  github_username: string
}

const DEFAULT_MEMBERS: MemberState[] = [
  { name: 'Alice', github_username: 'alice-dev' },
  { name: 'Bob', github_username: 'bob-codes' },
  { name: 'Charlie', github_username: 'charlie-eng' },
  { name: 'Dana', github_username: 'dana-tech' },
  { name: 'Evan', github_username: 'evan-builder' },
  { name: 'Fiona', github_username: 'fiona-hacks' },
]

const INSPIRATION_PRESETS = [
  {
    title: '🎨 Real-Time Whiteboard',
    prompt: 'A real-time collaborative whiteboard app with live cursor tracking, voice channels, and interactive canvas drawing for hackathon teams.',
  },
  {
    title: '🤖 DevOps Incident AI',
    prompt: 'An AI-powered DevOps agent that monitors cloud alerts, inspects container logs, diagnoses root causes, and suggests incident remediation scripts.',
  },
  {
    title: '🏃 Health & Habit Tracker',
    prompt: 'A wellness and habit tracker that logs daily routines, provides AI coaching insights, and gamifies team fitness challenges.',
  },
  {
    title: '🛡️ Web3 Smart Contract Auditor',
    prompt: 'A static analysis security tool that scans Solidity smart contracts for reentrancy and access-control vulnerabilities with interactive remediation diffs.',
  },
]

export default function ProjectForm({ onSuccess }: ProjectFormProps) {
  // Step 1: Team Setup
  const [teamName, setTeamName] = useState('HackSquad')
  const [teamSize, setTeamSize] = useState<number>(3)
  const [members, setMembers] = useState<MemberState[]>(DEFAULT_MEMBERS.slice(0, 3))

  // Step 2: Problem Statement
  const [ideaPrompt, setIdeaPrompt] = useState('')
  const [decomposing, setDecomposing] = useState(false)
  const [decomposeError, setDecomposeError] = useState<string | null>(null)

  // Step 3: Divided Work (Generated by AI)
  const [divided, setDivided] = useState(false)
  const [projectName, setProjectName] = useState('')
  const [techStack, setTechStack] = useState('')
  const [conventions, setConventions] = useState('')
  const [summary, setSummary] = useState('')
  const [allocatedTeammates, setAllocatedTeammates] = useState<TeammateInput[]>([])

  // GitHub Launch Options
  const [isDemo, setIsDemo] = useState(true)
  const [githubPat, setGithubPat] = useState('')
  const [isPrivate, setIsPrivate] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [submitProgress, setSubmitProgress] = useState<string | null>(null)
  const [submitError, setSubmitError] = useState<string | null>(null)

  // Adjust member list when teamSize changes
  const handleTeamSizeChange = (newSize: number) => {
    setTeamSize(newSize)
    setMembers((prev) => {
      const next = [...prev]
      while (next.length < newSize) {
        const fallback = DEFAULT_MEMBERS[next.length] || {
          name: `Teammate ${next.length + 1}`,
          github_username: `member-${next.length + 1}`,
        }
        next.push(fallback)
      }
      return next.slice(0, newSize)
    })
  }

  // Update a single member's name or handle
  const handleMemberChange = (index: number, field: keyof MemberState, value: string) => {
    setMembers((prev) =>
      prev.map((m, idx) => (idx === index ? { ...m, [field]: value } : m))
    )
  }

  // Divide the work via AI (Grok / Groq / Fallback)
  const handleDivideWork = async (promptOverride?: string) => {
    const promptToUse = promptOverride || ideaPrompt
    if (!promptToUse.trim()) {
      setDecomposeError('Please describe what your team is building (or select an idea preset).')
      return
    }

    setDecomposing(true)
    setDecomposeError(null)

    try {
      const payload = {
        teamName: teamName.trim() || 'my-project',
        teamSize,
        teammateRoles: members.slice(0, teamSize).map((m) => ({
          name: m.name.trim() || 'Teammate',
          githubUsername: m.github_username.trim().replace(/^@/, '') || 'member',
        })),
        ideaPrompt: promptToUse.trim(),
      }

      const res = await fetch('/api/ai/decompose', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      })

      const data = await res.json()
      if (!res.ok || !data.success) {
        throw new Error(data.error || 'Failed to divide work')
      }

      const result = data.data
      setProjectName(result.projectName)
      setSummary(result.description)
      setTechStack(result.techStack)
      setConventions(result.sharedConventions)
      setAllocatedTeammates(
        result.teammates.map((tm: any) => ({
          name: tm.name,
          github_username: tm.githubUsername,
          task_description: tm.taskDescription,
          owned_paths: tm.ownedPaths,
        }))
      )
      setDivided(true)

      // Smooth scroll to divided section
      setTimeout(() => {
        const el = document.getElementById('step-divided-work')
        if (el) el.scrollIntoView({ behavior: 'smooth' })
      }, 100)
    } catch (err: any) {
      setDecomposeError(err.message || 'An error occurred while dividing the work.')
    } finally {
      setDecomposing(false)
    }
  }

  // Final Launch & Provision
  const handleLaunch = async (e: React.FormEvent) => {
    e.preventDefault()
    setSubmitError(null)
    setSubmitting(true)
    setSubmitProgress('Saving project brief...')

    try {
      const projectPayload: ProjectInput = {
        name: projectName || teamName.toLowerCase().replace(/[^a-z0-9-_]/g, '-'),
        description: summary.trim(),
        tech_stack: techStack.trim(),
        shared_conventions: conventions.trim(),
        teammates: allocatedTeammates,
      }

      // 1. Create project in backend
      const res = await fetch('/api/projects', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(projectPayload),
      })

      if (!res.ok) {
        const errData = await res.json()
        throw new Error(errData.error || 'Failed to create project')
      }

      const project: Project = await res.json()

      // 2. Provision repo & cut branches
      setSubmitProgress('Provisioning repository and cutting teammate branches...')
      const provisionRes = await fetch(`/api/projects/${project.id}/provision`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          pat: githubPat.trim() || undefined,
          repoName: projectName || undefined,
          isPrivate,
          isDemo: isDemo || !githubPat.trim(),
        }),
      })

      if (provisionRes.ok) {
        const provData: ProvisionResult = await provisionRes.json()
        project.github_repo_url = provData.repoUrl
        onSuccess(project, provData)
      } else {
        onSuccess(project)
      }
    } catch (err: any) {
      setSubmitError(err.message || 'Failed to launch project')
    } finally {
      setSubmitting(false)
      setSubmitProgress(null)
    }
  }

  return (
    <div className="project-form" id="simple-project-form">
      {/* Page Header */}
      <div className="form-header">
        <div className="ai-modal-badge mono">🌿 BRANCHOUT</div>
        <h1 style={{ marginTop: '4px' }}>Simple Team & Project Setup</h1>
        <p className="form-subtitle">
          Enter your team details and idea. The AI will divide the work into isolated, conflict-free tasks and branches.
        </p>
      </div>

      {/* ============================================================ */}
      {/* STEP 1: TEAM NAME, TEAM SIZE, & MEMBER NAMES                 */}
      {/* ============================================================ */}
      <section className="form-section" id="step-team-setup">
        <h2 className="section-title">
          <span className="section-icon mono">01</span>
          Team Setup
        </h2>

        {/* Team Name & Size Row */}
        <div className="field-row two-col">
          <div className="field">
            <label htmlFor="input-team-name" className="field-label">
              Team / Project Name
            </label>
            <input
              id="input-team-name"
              type="text"
              className="input mono"
              placeholder="e.g. CloudNavigators"
              value={teamName}
              onChange={(e) => setTeamName(e.target.value)}
              required
            />
          </div>

          <div className="field">
            <label htmlFor="select-team-size" className="field-label">
              Team Size
            </label>
            <select
              id="select-team-size"
              className="input select-input mono"
              value={teamSize}
              onChange={(e) => handleTeamSizeChange(parseInt(e.target.value, 10))}
            >
              <option value={2}>2 Teammates</option>
              <option value={3}>3 Teammates</option>
              <option value={4}>4 Teammates</option>
              <option value={5}>5 Teammates</option>
              <option value={6}>6 Teammates</option>
            </select>
          </div>
        </div>

        {/* Member Names & GitHub Handles */}
        <div style={{ marginTop: 'var(--space-sm)' }}>
          <span className="field-label mono">TEAM MEMBERS:</span>
          <div className="members-grid">
            {members.slice(0, teamSize).map((member, idx) => (
              <div key={idx} className="member-card-setup">
                <div className="member-card-header">
                  <span className="member-number-badge">MEMBER {idx + 1}</span>
                </div>

                <div className="field-row two-col" style={{ gap: 'var(--space-xs)' }}>
                  <div className="field">
                    <input
                      type="text"
                      className="input mono"
                      style={{ fontSize: '0.8125rem', padding: '6px 8px' }}
                      placeholder="Name"
                      value={member.name}
                      onChange={(e) => handleMemberChange(idx, 'name', e.target.value)}
                      required
                    />
                  </div>
                  <div className="field">
                    <div style={{ display: 'flex', alignItems: 'center' }}>
                      <span className="mono muted" style={{ marginRight: '4px', fontSize: '0.8125rem' }}>@</span>
                      <input
                        type="text"
                        className="input mono"
                        style={{ fontSize: '0.8125rem', padding: '6px 8px' }}
                        placeholder="github-handle"
                        value={member.github_username}
                        onChange={(e) => handleMemberChange(idx, 'github_username', e.target.value)}
                        required
                      />
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/* STEP 2: PROBLEM STATEMENT & DIVIDE WORK                      */}
      {/* ============================================================ */}
      <section className="form-section" id="step-problem-statement">
        <h2 className="section-title">
          <span className="section-icon mono">02</span>
          Problem Statement
        </h2>

        <p className="section-description">
          Describe what you want to build. You can also pick a preset idea below to start instantly.
        </p>

        {/* Quick Inspiration Presets */}
        <div className="ai-preset-chips">
          {INSPIRATION_PRESETS.map((preset, idx) => (
            <button
              key={idx}
              type="button"
              className="ai-preset-chip"
              onClick={() => {
                setIdeaPrompt(preset.prompt)
                setDecomposeError(null)
                handleDivideWork(preset.prompt)
              }}
            >
              {preset.title}
            </button>
          ))}
        </div>

        {/* Textarea */}
        <div className="field" style={{ marginTop: 'var(--space-sm)' }}>
          <textarea
            id="idea-prompt-input"
            className="input textarea mono"
            rows={3}
            placeholder="e.g. An automated drone delivery platform that schedules flights and runs collision avoidance..."
            value={ideaPrompt}
            onChange={(e) => setIdeaPrompt(e.target.value)}
          />
        </div>

        {decomposeError && (
          <div className="error-banner" style={{ marginTop: 'var(--space-xs)' }}>
            {decomposeError}
          </div>
        )}

        {/* Main Action Button */}
        <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: 'var(--space-sm)' }}>
          <button
            type="button"
            className="btn btn-primary"
            style={{ fontSize: '0.9375rem', padding: '10px 20px' }}
            onClick={() => handleDivideWork()}
            disabled={decomposing || !ideaPrompt.trim()}
            id="btn-divide-work"
          >
            {decomposing ? (
              <>
                <span className="spinner" style={{ width: 14, height: 14, marginRight: '8px' }} />
                <span>Dividing Work & Allocating Paths...</span>
              </>
            ) : divided ? (
              '🔄 Re-Divide Work'
            ) : (
              '✨ Divide & Allocate Work'
            )}
          </button>
        </div>
      </section>

      {/* ============================================================ */}
      {/* STEP 3: DIVIDED WORK & LAUNCH                                */}
      {/* ============================================================ */}
      {divided && (
        <form onSubmit={handleLaunch} id="step-divided-work">
          <section className="form-section">
            <div className="section-title-row">
              <h2 className="section-title">
                <span className="section-icon mono">03</span>
                Divided Work Plan
              </h2>
              <span className="security-tag mono" style={{ color: 'var(--accent)' }}>
                ✓ Zero Merge Conflicts Guaranteed
              </span>
            </div>

            {/* Architecture Overview Pill */}
            <div className="clean-callout">
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span className="mono" style={{ color: 'var(--accent)', fontWeight: 600, fontSize: '0.875rem' }}>
                  📦 {projectName}
                </span>
                <span className="mono muted" style={{ fontSize: '0.75rem' }}>
                  {techStack}
                </span>
              </div>
              <p style={{ fontSize: '0.8125rem', color: 'var(--text-secondary)', margin: 0 }}>
                {summary}
              </p>
            </div>

            {/* Clean Teammate Allocation Cards */}
            <div className="divided-work-list">
              {allocatedTeammates.map((mate, i) => (
                <div key={i} className="divided-card">
                  <div className="divided-card-head">
                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                      <span className="divided-name">{mate.name}</span>
                      <span className="mono muted" style={{ fontSize: '0.8125rem' }}>
                        @{mate.github_username}
                      </span>
                    </div>
                    <span className="mono muted" style={{ fontSize: '0.75rem' }}>
                      ↳ <code>{`${mate.task_description.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 18)}-${mate.github_username}`}</code>
                    </span>
                  </div>

                  <div className="divided-task-text">
                    <strong>Assigned:</strong> {mate.task_description}
                  </div>

                  <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <span className="field-label mono" style={{ fontSize: '0.6875rem' }}>Isolated Paths:</span>
                    <div className="ai-tm-paths mono">
                      {mate.owned_paths.map((p, idx) => (
                        <span key={idx} className="path-tag">
                          {p}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {/* Launch / GitHub Provisioning */}
            <div style={{ marginTop: 'var(--space-md)', paddingTop: 'var(--space-md)', borderTop: '1px solid var(--border-subtle)' }}>
              <div className="field-row two-col" style={{ alignItems: 'center' }}>
                <div className="field">
                  <label className="checkbox-label demo-toggle" style={{ fontSize: '0.8125rem', cursor: 'pointer' }}>
                    <input
                      type="checkbox"
                      checked={isDemo}
                      onChange={(e) => setIsDemo(e.target.checked)}
                      id="is-demo-checkbox"
                    />
                    <span>⚡ <strong>Demo Mode</strong> (Instantly simulate GitHub repository & branches)</span>
                  </label>
                </div>

                {!isDemo && (
                  <div className="field">
                    <input
                      type="password"
                      className="input mono"
                      placeholder="Optional: GitHub PAT (ghp_...)"
                      value={githubPat}
                      onChange={(e) => setGithubPat(e.target.value)}
                    />
                    <label className="checkbox-label" style={{ marginTop: '4px', fontSize: '0.75rem' }}>
                      <input
                        type="checkbox"
                        checked={isPrivate}
                        onChange={(e) => setIsPrivate(e.target.checked)}
                      />
                      <span>Private Repository</span>
                    </label>
                  </div>
                )}
              </div>
            </div>

            {submitError && (
              <div className="error-banner" style={{ marginTop: 'var(--space-sm)' }}>
                {submitError}
              </div>
            )}

            {submitProgress && (
              <div className="progress-banner" style={{ marginTop: 'var(--space-sm)' }}>
                <span className="spinner" />
                <span>{submitProgress}</span>
              </div>
            )}

            {/* Launch Button */}
            <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: 'var(--space-md)' }}>
              <button
                type="submit"
                className="btn btn-primary"
                style={{ fontSize: '1rem', padding: '12px 24px' }}
                disabled={submitting}
                id="submit-btn"
              >
                {submitting ? 'Launching Team...' : '🚀 Launch Team & Cut Branches'}
              </button>
            </div>
          </section>
        </form>
      )}
    </div>
  )
}
