import type { ProjectActivityReport, BranchActivity } from "./activityTracker.js";

/**
 * Generates an end-of-hackathon Markdown summary for project submissions,
 * Devpost writeups, or team retrospectives.
 */
export function generateMarkdownSummary(report: ProjectActivityReport, projectDetails?: any): string {
  const sections: string[] = [];

  // Header
  sections.push(`# Hackathon Contribution Summary: ${report.projectName}`);
  sections.push(`*Generated by Branchout — Hackathon Team Coordinator*\n`);

  // Project Overview
  sections.push(`## 📌 Project Overview`);
  sections.push(`- **Project Name:** ${report.projectName}`);
  if (projectDetails?.description) {
    sections.push(`- **Description:** ${projectDetails.description}`);
  }
  if (projectDetails?.tech_stack) {
    sections.push(`- **Tech Stack:** \`${projectDetails.tech_stack}\``);
  }
  if (report.githubRepoUrl) {
    sections.push(`- **GitHub Repository:** [${report.githubRepoUrl}](${report.githubRepoUrl})`);
  }
  sections.push(`- **Generated At:** ${new Date().toUTCString()}\n`);

  // Key Metrics
  sections.push(`## 📊 Team Metrics`);
  sections.push(`| Metric | Value |`);
  sections.push(`| :--- | :--- |`);
  sections.push(`| **Team Members** | ${report.branches.length} |`);
  sections.push(`| **Total Commits** | ${report.totalCommits} |`);
  sections.push(`| **Active Branches** | ${report.activeBranchesCount} / ${report.branches.length} |`);
  sections.push(`| **Open Pull Requests** | ${report.openPrCount} |`);
  sections.push(`| **Stale Branches** | ${report.staleBranchesCount} |`);
  sections.push(``);

  // Individual Contributions Breakdown
  sections.push(`## 👥 Individual Contribution Breakdown`);
  sections.push(`| Teammate | GitHub | Assigned Branch | Commits | Last Active | PR Status | Self Status | Alignment |`);
  sections.push(`| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |`);

  for (const b of report.branches) {
    const lastActive = b.lastCommitAt ? new Date(b.lastCommitAt).toLocaleString() : 'No commits';
    const pr = b.prStatus !== 'none' ? (b.prUrl ? `[PR #${b.prNumber || '1'}](${b.prUrl}) (${b.prStatus})` : b.prStatus) : 'None';
    const statusText = b.status.replace('_', ' ').toUpperCase();
    
    // Check mismatch
    let alignment = '✅ Aligned';
    if (b.status === 'done' && b.commitCount === 0) {
      alignment = '⚠️ Mismatch (Done w/ 0 commits)';
    } else if (b.status === 'not_started' && b.commitCount > 0) {
      alignment = 'ℹ️ Active (Status not updated)';
    } else if (b.isStale) {
      alignment = '⏳ Inactive';
    }

    sections.push(
      `| **${b.teammateName}** | [@${b.githubUsername}](https://github.com/${b.githubUsername}) | \`${b.branchName}\` | **${b.commitCount}** | ${lastActive} | ${pr} | \`${statusText}\` | ${alignment} |`
    );
  }

  sections.push(``);

  // Task & Path Assignments Detail
  sections.push(`## 📁 Assigned Tasks & File Ownership`);
  for (const b of report.branches) {
    sections.push(`### 🌿 ${b.teammateName} (@${b.githubUsername})`);
    sections.push(`- **Branch:** \`${b.branchName}\``);
    sections.push(`- **Self-Reported Status:** \`${b.status.replace('_', ' ').toUpperCase()}\``);
    if (b.ownedPaths.length > 0) {
      sections.push(`- **Owned Paths:** ${b.ownedPaths.map((p) => `\`${p}\``).join(', ')}`);
    }
    if (b.lastCommitMessage) {
      sections.push(`- **Latest Commit:** \`${b.lastCommitSha}\` — *${b.lastCommitMessage}*`);
    }
    sections.push(``);
  }

  sections.push(`---\n*Exported from Branchout Hackathon Coordinator*`);
  return sections.join('\n');
}

/**
 * Generates an end-of-hackathon CSV export.
 */
export function generateCsvSummary(report: ProjectActivityReport): string {
  const headers = [
    "Teammate",
    "GitHub Username",
    "Branch Name",
    "Total Commits",
    "Last Commit At",
    "Latest Commit SHA",
    "Latest Commit Message",
    "PR Status",
    "PR URL",
    "Self Reported Status",
    "Is Stale",
    "Owned Paths",
  ];

  const rows = report.branches.map((b) => [
    escapeCsv(b.teammateName),
    escapeCsv(b.githubUsername),
    escapeCsv(b.branchName),
    b.commitCount.toString(),
    escapeCsv(b.lastCommitAt || "N/A"),
    escapeCsv(b.lastCommitSha || "N/A"),
    escapeCsv(b.lastCommitMessage || "N/A"),
    escapeCsv(b.prStatus),
    escapeCsv(b.prUrl || "N/A"),
    escapeCsv(b.status),
    b.isStale ? "YES" : "NO",
    escapeCsv(b.ownedPaths.join("; ")),
  ]);

  return [headers.join(","), ...rows.map((r) => r.join(","))].join("\n");
}

function escapeCsv(val: string): string {
  if (val.includes(",") || val.includes('"') || val.includes("\n")) {
    return `"${val.replace(/"/g, '""')}"`;
  }
  return val;
}
